config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#index"
  resources :items, :path => "images", only: [:show] do 
    resources :pictures, only: [:create, :edit]
  end 
  post '/add_to_cart/:item_id' => 'carts#add_to_cart', :as => 'add_to_cart'
  resources :carts, only: [:show]
  resources :orders, only: [ :show], :path => "commandes"
  resources :users, only: [:show]
  resources :charges
  resources :transactions, only: [:create, :destroy]
  resources :mon_paniers, only: [:index], :path => "mon_panier"
  resources :mon_profils, only: [:index], :path => "mon_profil"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :transactions
  has_many :items, through: :transactions

  def add_item(item_id)
      Transaction.create(cart_id: self.id, item_id: item_id)
  end

  def remove_item(item_id)
    t = Transaction.find_by(item_id: item_id)
    t.destroy
  end

  # clear the cart
  def empty_cart
    self.transactions.destroy_all
  end
end

app/models/item.rb
class Item < ApplicationRecord
	validates :title, 
		presence: true,
		length: { minimum: 3 }
	validates :description,
		presence: true,
		length: { minimum: 40 }
	validates :price,
		presence: true,
		numericality: { greater_than_or_equal_to: 1 }
	validates :image_url,
		presence: true
  
  # ASSOCIATIONS
  # 1 - N with order_lines
  has_many :order_lines
  # N - N with orders
  has_many :orders, through: :order_lines

  # 1 - N with transactions
  has_many :transactions
  # N - N with carts
	has_many :carts, through: :transactions
  # active storage 
    has_one_attached :picture
end

app/models/order.rb
class Order < ApplicationRecord
  # ASSOCIATIONS
  # N - 1 with users
  belongs_to :user
  
  # 1 - N with order_lines
  has_many :order_lines
  # N - N with items
  has_many :items, through: :order_lines

  # fill order at creation
  after_create :retrieve_cart_items

  # transfer all cart items in order as order lines
  def retrieve_cart_items
    self.user.cart.transactions.each do |transaction|
      self.order_lines.create!(
        order_id: self.id,
        item_id: transaction.item_id
      )
    end
  end

  # update the order's total amount
  def update_total
    self.total = 0
    self.order_lines.each do |order_line|
      self.total += order_line.item.price
    end
    self.save!()
  end
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  # ASSOCIATIONS
  # N - 1 with orders
  belongs_to :order
  # N - 1 with items
  belongs_to :item
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :cart
    belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  # ASSOCIATIONS
  # 1 - 1 with carts
  has_one :cart

  # 1 - N with orders
  has_many :orders

  after_create :create_cart

  private

  def create_cart
    self.cart = Cart.create!(user_id: self.id)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    include CartsHelper
    before_action :current_cart, only: [:add_to_cart, :remove_from_cart]
    before_action :authenticate_user!, only: [:show, :remove_from_cart, :add_to_cart]

    def add_to_cart
        @item = Item.find(params[:item_id])
        current_cart.add_item(@item.id)
        flash[:success] = "La photo #{@item.title} a bien été ajoutée au panier"
        redirect_back(fallback_location: root_path)
    end

    def show
        current_user_must_own_cart
		@transactions = Cart.find(params[:id]).transactions
		@total_price = []
    end

    private

    def current_user_must_own_cart
        @cart = Cart.find(params[:id])
        if current_cart.id != @cart.id
            flash[:error] = "Vous n'avez pas accès à ce panier"
            redirect_to root_path
        end
    end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def new
    @user = current_user
    @order = current_user.orders.create!()
    @items = current_user.cart.items
  end

def create
  
  # retrieve the order
  @order = current_user.orders.last
  @order.update_total
  # Amount in cents
  @amount = (@order.total * 100).to_i

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'inr',
  })

  if charge
    @order.update!(stripe_customer_id: charge.customer)
    current_user.cart.empty_cart
    UserMailer.ordered_email(current_user, @order).deliver_now

    flash[:success] = "Paiement validé - commande validée - expédition en cours...\n
    Votre facture vous a été envoyé par email."
    redirect_to root_path
  else
    @order.destroy
    flash.now[:danger] = "Une erreur s'est produite - veuillez ré-essayer. Promis, on ne vous fera pas payer deux fois..."
    redirect_back(fallback_location: root_path)
  end

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
  end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @items = @order.items
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit]

  def show
  	current_user_must_own_profile
  	@orders = User.find(params[:id]).orders
  	@user = User.find(params[:id])
  end

  private

  def current_user_must_own_profile
  	@user = User.find(params[:id])
  	if current_user.id != @user.id
  		flash[:error] = "Vous n'avez pas accès à ce profil"
  		redirect_to root_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for_flash(type)
        case type
          when 'notice' then "alert-info"
          when 'success' then "alert-success"
          when 'error' then "alert-danger"
          when 'alert' then "alert-warning"
        end
      end
end

app/helpers/carts_helper.rb
module CartsHelper
    def current_cart
        return current_user.cart
    end 
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mon_paniers_helper.rb
module MonPaniersHelper
end

app/helpers/mon_profils_helper.rb
module MonProfilsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="container">
  <h2>Contenu du panier :</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titre de la photo</th>
        <th scope="col">Prix</th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.all.each do |transaction| %>
      <tr>
        <th scope="row"><%= transaction.item.id %></th>
        <td><%= transaction.item.title %></td>
        <td><%= transaction.item.price %></td>
        <% @total_price << transaction.item.price %>
        <td>
          <%= link_to "Retirer du panier", transaction_path(transaction.id), method: :delete, class: "btn btn-danger" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <p>Le panier fait un total de <%= @total_price.sum %> roupies.</p>
  </div>
  <div>
    <%= link_to 'Valider votre commande', new_charge_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/items/index.html.erb
<div class="container-fluid px-0">

  <div class="jumbotron bg-primary border border-success">
      <div class="container">
        <h1 class="display-4">
          Photos de snowboard en noir et blanc <br/> <small>parce que c'est de saison</small>
        </h1>
        <p class="lead">
          Tu vas voir notre collec est top, par contre j'espère que t'as des roupies sur toi 
        </p>
      </div> <!-- /container -->
    </div> <!-- /jumbotron -->

  <div class="row w-75 mx-auto">
    <!-- Display all the items in cards -->
    <% @items.each do |item| %>
      <div class='col-md-4 col-lg-3 p-3'>
        <div class="card border border-primary">
        <%if item.picture.attached?%>
          <%= image_tag item.picture, class: "w-100", alt: 'picture' %>
        <%else%>
          <p>=== random pix ===</p>
          <img src="<%= item.image_url %>%" class="card-img-top border-circle" alt="product image">
        <%end%>
          <div class="card-body">
            <h3 class="card-title text-primary"><%= item.title %></h3>
            <h5 class="card-title"><%= item.price %> roupies</h5>
            <p class="card-text text-muted"><%= item.description %></p>
            <hr>
            <% if user_signed_in? %>
            <p><%= button_to "Ajouter au panier", add_to_cart_path(:item_id => item.id), {:method => :post, :class => "btn btn-primary"} %></p>
            <% end %>
            <p><%= link_to 'Détails', item_path(item), { :class => "btn btn-outline-secondary" } %></p>
          </div> <!-- /card-body-->
        </div> <!-- /card -->
      </div> <!-- /card column -->
    <% end %>
    <!-- End of items card display -->
  </div> <!-- /row -->
</div><!-- /container-fluid-->

app/views/items/show.html.erb
<div class="container-fluid">
  <div class="row p-5">
    
    <div class="col-md-6 py-5 pl-5">
      <%if @item.picture.attached?%>
        <%= image_tag @item.picture, class: "w-100", alt: 'picture' %>
      <%else%>
        <p>=== random pix ===</p>
        <img src="<%= @item.image_url %>" alt="item image">
      <%end%>
    </div> <!-- /col-md-6-->

    <div class="col-md-6 pr-5 d-flex">
      <div class="card border my-auto">
        <div class="card-body">
          <h5 class="card-title"><%= @item.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= @item.price %> roupies</h6>
          <p class="card-text"><%= @item.description %></p>
          <% if user_signed_in? %>
          <%= button_to "Ajouter au panier", add_to_cart_path(:item_id => @item.id), {:method => :post, :class => "btn btn-success"} %>
          <% end %>
        </div>
      </div>
    </div>
    <div> <!-- active storage -->
     <%= form_tag item_pictures_path(@item), multipart: true do %>
      <%= file_field_tag :picture %>
      <%= submit_tag "uploader une photo" %>
    <% end %>
    </div>

  </div> <!-- / row -->
</div><!-- /container-fluid -->

app/views/orders/show.html.erb
<div class="container">
  <h2>Récapitulatif de votre commande :</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titre de la photo</th>
        <th scope="col">Prix</th>
      </tr>
    </thead>
    <tbody>
      <% @items.all.each do |item| %>
      <tr>
        <th scope="row"><%= item.id %></th>
        <td><%= item.title %></td>
        <td><%= item.price %></td>
        <% @order.total += item.price %>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <p>Montant de la commande : <%= @order.total %> roupies.</p>
  </div>
  <div>
    <%= button_to 'Payer', '#', class: 'btn btn-danger' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<h1>Bienvenue sur votre profil !</h1>
</div>

<div class="container">
  <ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="" data-target="#profil_details" data-toggle="tab" class="nav-link active">Profil</a>
    </li>
    <li class="nav-item">
        <a href="" data-target="#user_orders" data-toggle="tab" class="nav-link">Commandes</a>
    </li>
        </ul>
        <div class="tab-content py-4">
            <div class="tab-pane active" id="profil_details">
              <table class='table table-borderless'>
                <tbody>
                  <tr>
                    <th><h3 class='text-secondary'>Prénom</h3></th>
                    <td><p><%= @user.first_name %></p></td>
                  </tr>
                  <tr>
                    <th><h3 class='text-secondary'>Nom</h3></th>
                    <td><p><%= @user.last_name %></p></td>
                  </tr>
                  <tr>
                    <th><h3 class='text-secondary'>Email</h3></th>
                    <td><p><%= @user.email %></p></td>
                  </tr>
                </tbody>
              </table>
            </div> <!-- /tab-pane -->

            <div class="tab-pane" id="user_orders">
              <table class="table table-hover table">
                <thead class='thead-light'>
                  <tr>
                    <th><h4 class='text-secondary'>N° de commande</h4></th>
                    <th><h4 class='text-secondary'>Contenu</h4></th>
                    <th><h4 class='text-secondary'>Montant</h4></th>
                    <th><h4 class='text-secondary'>Date de commande</h4></th>                    
                  </tr>
                </thead> 
                <tbody>
                  <% @orders.each do |order| %>
                  <tr>
                    <td><h6><%= order.id %></h6></td>
				            <td>
				              <% order.items.each do |item| %>
				                <%= item.title %>
				                <br>
		                 <% end %>
		    	          </td>
                    <td><%= order.total %></td>
                    <td><%= order.created_at %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div> <!-- /tab-pane -->
  <%= link_to "Modifier votre profil", edit_user_registration_path, class: "btn btn-success" %>
</div><!-- /container -->