config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "items#index"
  resources :items, :path => "images", only: [:show] do 
    resources :pictures, only: [:create, :edit]
  end 
  post '/add_to_cart/:item_id' => 'carts#add_to_cart', :as => 'add_to_cart'
  resources :carts, only: [:show]
  resources :orders, only: [ :show], :path => "commandes"
  resources :users, only: [:show]
  resources :charges
  resources :transactions, only: [:create, :destroy]
  resources :mon_paniers, only: [:index], :path => "mon_panier"
  resources :mon_profils, only: [:index], :path => "mon_profil"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :transactions
  has_many :items, through: :transactions

  def add_item(item_id)
      Transaction.create(cart_id: self.id, item_id: item_id)
  end

  def remove_item(item_id)
    t = Transaction.find_by(item_id: item_id)
    t.destroy
  end

  # clear the cart
  def empty_cart
    self.transactions.destroy_all
  end
end

app/models/item.rb
class Item < ApplicationRecord
	validates :title, 
		presence: true,
		length: { minimum: 3 }
	validates :description,
		presence: true,
		length: { minimum: 40 }
	validates :price,
		presence: true,
		numericality: { greater_than_or_equal_to: 1 }
	validates :image_url,
		presence: true
  
  # ASSOCIATIONS
  # 1 - N with order_lines
  has_many :order_lines
  # N - N with orders
  has_many :orders, through: :order_lines

  # 1 - N with transactions
  has_many :transactions
  # N - N with carts
	has_many :carts, through: :transactions
  # active storage 
    has_one_attached :picture
end

app/models/order.rb
class Order < ApplicationRecord
  # ASSOCIATIONS
  # N - 1 with users
  belongs_to :user
  
  # 1 - N with order_lines
  has_many :order_lines
  # N - N with items
  has_many :items, through: :order_lines

  # fill order at creation
  after_create :retrieve_cart_items

  # transfer all cart items in order as order lines
  def retrieve_cart_items
    self.user.cart.transactions.each do |transaction|
      self.order_lines.create!(
        order_id: self.id,
        item_id: transaction.item_id
      )
    end
  end

  # update the order's total amount
  def update_total
    self.total = 0
    self.order_lines.each do |order_line|
      self.total += order_line.item.price
    end
    self.save!()
  end
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  # ASSOCIATIONS
  # N - 1 with orders
  belongs_to :order
  # N - 1 with items
  belongs_to :item
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :cart
    belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  # ASSOCIATIONS
  # 1 - 1 with carts
  has_one :cart

  # 1 - N with orders
  has_many :orders

  after_create :create_cart

  private

  def create_cart
    self.cart = Cart.create!(user_id: self.id)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    include CartsHelper
    before_action :current_cart, only: [:add_to_cart, :remove_from_cart]
    before_action :authenticate_user!, only: [:show, :remove_from_cart, :add_to_cart]

    def add_to_cart
        @item = Item.find(params[:item_id])
        current_cart.add_item(@item.id)
        flash[:success] = "La photo #{@item.title} a bien été ajoutée au panier"
        redirect_back(fallback_location: root_path)
    end

    def show
        current_user_must_own_cart
		@transactions = Cart.find(params[:id]).transactions
		@total_price = []
    end

    private

    def current_user_must_own_cart
        @cart = Cart.find(params[:id])
        if current_cart.id != @cart.id
            flash[:error] = "Vous n'avez pas accès à ce panier"
            redirect_to root_path
        end
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for_flash(type)
        case type
          when 'notice' then "alert-info"
          when 'success' then "alert-success"
          when 'error' then "alert-danger"
          when 'alert' then "alert-warning"
        end
      end
end

app/helpers/carts_helper.rb
module CartsHelper
    def current_cart
        return current_user.cart
    end 
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mon_paniers_helper.rb
module MonPaniersHelper
end

app/helpers/mon_profils_helper.rb
module MonProfilsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
  <% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show mb-0" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ThpKittiesDealers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/f1f069f515.js" crossorigin="anonymous"></script>
</head>




<body>

  <!--ATTRIBUTS NAVBAR-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!--ICONE CHAT - URL : https://fontawesome.com/icons/cat?style=solid-->
    <%= link_to root_path, class: "text-dark mr-2" do %>
    <%= fa_icon "cat 4x" %>
    <% end %>

    <!--BOUTON BURGER QUI S'AFFICHE SUR PETIT ECRAN-->
    <button class="navbar-toggler border" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!--ATTRIBUTS NAVBAR-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!--GROUPE BOUTONS DE GAUCHE-->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Kitties Dealers Inc", root_path, class: "text-dark nav-link mx-2" %>
        </li>
      </ul>


      <!-- BARRE DE RECHERCHE - FORME-->
      <form class="form-inline my-2 my-lg-0 mx-2 w-100">
        <!-- BARRE DE RECHERCHE - CONTENU-->
        <input class="form-control mr-sm-2 mx-3 w-75 text-left" type="search" placeholder="Search"
          aria-label="Search">
        <!-- BOUTON SEARCH-->
        <button class="btn btn-secondary my-2 my-sm-0 mx-3" type="submit">Search</button>
      </form>


      <!--BOUTONS CONNEXION AU COMPTE + PANIER-->
      <ul class="navbar-nav mr-auto">

        <!--BOUTONS DE PANIER - url : https://fontawesome.com/icons?d=gallery&q=CART-->
        <% if user_signed_in? %>
        <li class="nav-item">
        <div class="text-center">
          <%= link_to mon_paniers_path, class: "nav-link" do %>
            <span><i class="fas fa-shopping-cart fa-2x" aria-hidden="true"></i></span>
            <span class="badge badge-pill badge-primary"><%= current_cart.items.length %> </span>
          <% end %>
        </div>
        </li>
        <% end %>

        <!--BOUTONS POUR ESPACE DE SEPARATION-->
        <li class="nav-item">
          <i class="nav-link disabled"></i>
        </li>


        <!--COMPTE CONNECTE-->
        <% if user_signed_in? %>

        <!--BOUTONS DEPLIANT DE CONNEXION AU COMPTE-->
        <li class="nav-item dropdown">
          <!--TITRE DU BOUTON -> RESTE TOUJOURS AFFICHE-->
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <!-- SI PRENOM RENSEIGNE -->
            <% if current_user.first_name != nil && current_user.first_name != "" %>
              <%= current_user.first_name %>
            <!-- SI PAS DE PRENOM RENSEIGNE -->
            <% elsif current_user.first_name == nil || current_user.first_name == "" %>
              <%= current_user.email %>
            <% end %>
          </a>
          <!--BOUTONS QUI SE DEPLIENT-->
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", mon_profils_path, class: "dropdown-item" %>
            <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>


        <!--COMPTE DECONNECTE-->
        <% else %>

        <!--BOUTONS DEPLIANT DE CONNEXION AU COMPTE-->
        <li class="nav-item dropdown">
          <!--TITRE DU BOUTON -> RESTE TOUJOURS AFFICHE-->
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Mon compte
          </a>
          <!--BOUTONS QUI SE DEPLIENT-->
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Suivre une commande", new_user_session_path, class: "dropdown-item" %>
            <span class="glyphicon glyphicon-search"></span>
          </div>
        </li>
        <% end %>

      </ul> <!--UL DES BOUTONS DE CONNEXION-->
    </div>
    <!--DIV DE NAVBAR-->
  </nav>
<%= render 'layouts/flash'%>
<%= yield %>
</body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ThpKittiesDealers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/f1f069f515.js" crossorigin="anonymous"></script>
</head>




<body>

  <!--ATTRIBUTS NAVBAR-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!--ICONE CHAT - URL : https://fontawesome.com/icons/cat?style=solid-->
    <%= link_to root_path, class: "text-dark mr-2" do %>
    <%= fa_icon "cat 4x" %>
    <% end %>

    <!--BOUTON BURGER QUI S'AFFICHE SUR PETIT ECRAN-->
    <button class="navbar-toggler border" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!--ATTRIBUTS NAVBAR-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!--GROUPE BOUTONS DE GAUCHE-->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Kitties Dealers Inc', root_path, class: "text-dark nav-link mx-2 disabled" %>
        </li>
      </ul>


      <!-- BARRE DE RECHERCHE - FORME-->
      <form class="form-inline my-2 my-lg-0 mx-2 w-100">
        <!-- BARRE DE RECHERCHE - CONTENU-->
        <input class="form-control mr-sm-2 mx-3 w-75 text-center" type="search" placeholder="Search"
          aria-label="Search">
        <!-- BOUTON SEARCH-->
        <button class="btn btn-secondary my-2 my-sm-0 mx-3" type="submit">Search</button>
      </form>


      <!--BOUTONS DE CONNEXION AU COMPTE-->
      <ul class="navbar-nav mr-auto">
        <!--BOUTONS DE PANIER - url : https://fontawesome.com/icons?d=gallery&q=CART-->
        <% if user_signed_in? %>
        <li class="nav-item">
        <div class="text-center">
          <%= link_to cart_path(current_user.cart.id), class: "nav-link" do %>
            <span><i class="fas fa-shopping-cart fa-2x" aria-hidden="true"></i></span>
            <span class="badge badge-pill badge-primary"><%= current_cart.items.length %> </span>
          <% end %>
        </div>
        </li>

        <% end %>
        <!--BOUTONS POUR ESPACE DE SEPARATION-->
        <li class="nav-item">
          <i class="nav-link disabled"></i>
        </li>

        <% if user_signed_in? %>
        <!--BOUTONS DEPLIANT DE CONNEXION AU COMPTE-->
        <li class="nav-item dropdown">
          <!--TITRE DU BOUTON -> RESTE TOUJOURS AFFICHE-->
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <!--BOUTONS QUI SE DEPLIENT-->
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", root_path, class: "dropdown-item" %>
            <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

        <% else %>
        <!--BOUTONS DEPLIANT DE CONNEXION AU COMPTE-->
        <li class="nav-item dropdown">
          <!--TITRE DU BOUTON -> RESTE TOUJOURS AFFICHE-->
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Mon compte
          </a>
          <!--BOUTONS QUI SE DEPLIENT-->
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Suivre une commande</a>
            <span class="glyphicon glyphicon-search"></span>
          </div>
        </li>

        <% end %>

      </ul>






    </div>
    <!--DIV DE NAVBAR-->
  </nav>


  <%= yield %>
</body>

</html>